name: Link validation on master branch
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Run cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          command-prefix: yarn dlx
          install-command: yarn install --immutable
          build: yarn build-dev
          start: yarn serve-dev
          headless: true
          wait-on: 'http://localhost:9000/home/getting-started'
          wait-on-timeout: 5
          env: skip_external=true
          spec: |
            cypress/integration/links.test.ts
            cypress/integration/redirects.test.ts
      - name: Archive Cypress screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: |
            /home/runner/work/git-gatsby/git-gatsby/cypress/screenshots
          retention-days: 5
      - name: Notify slack
        if: failure()
        uses: slackapi/slack-github-action@v1.17.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rotating_light::rotating_light::rotating_light::link: Invalid internal link found on *<https://docs.launchdarkly.com|Production>* :rotating_light::rotating_light::rotating_light:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failed run"
                    },
                    "action_id": "view-action-${{github.run_id}}",
                    "url": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": ":github: Deploy triggered by ${{github.actor}}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
