name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Deploy to s3 production
    environment:
      name: production
      url: https://docs.launchdarkly.com/
    concurrency: prod_deploys
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch entire history to get Last Edit date for topics
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: yarn install --immutable
      - run: yarn build-deploy-prod
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX: 'Docs'
          LAUNCHDARKLY_CLIENT_SIDE_ID: ${{ secrets.PROD_LAUNCHDARKLY_CLIENT_SIDE_ID }}
          GATSBY_DATADOG_CLIENT_TOKEN: ${{ secrets.PROD_DATADOG_CLIENT_TOKEN }}
          GATSBY_DATADOG_RUM_APPLICATION_ID: ${{ secrets.DATADOG_RUM_APPLICATION_ID }}
          GATSBY_DATADOG_RUM_CLIENT_TOKEN: ${{ secrets.DATADOG_RUM_CLIENT_TOKEN }}
          GATSBY_TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
          SEGMENT_KEY: 'RUtph5AIOikMUv9vQUVqHrb6G2pALs0T'
          AWS_S3_BUCKET: 'launchdarkly-docs-production'
          AWS_HOSTNAME: 'docs.launchdarkly.com'
      - name: Notify slack
        if: failure()
        uses: slackapi/slack-github-action@v1.17.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rotating_light::rotating_light::rotating_light::rocket: Docs site failed to deploy to *<https://docs.launchdarkly.com|Production>*. :rotating_light::rotating_light::rotating_light:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failed run"
                    },
                    "action_id": "view-action-${{github.run_id}}",
                    "url": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": ":github: Deploy triggered by ${{github.actor}}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cypress run
        timeout-minutes: 5
        uses: cypress-io/github-action@v2
        with:
          command-prefix: yarn dlx
          install-command: yarn install --immutable
          build: yarn build-nav-data
          headless: true
          config: baseUrl=http://docs.launchdarkly.com
          spec: cypress/integration/smoke.test.ts
      - name: Archive Cypress screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: |
            /home/runner/work/git-gatsby/git-gatsby/cypress/screenshots
          retention-days: 5
      - name: Notify slack
        if: failure()
        uses: slackapi/slack-github-action@v1.17.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rotating_light::rotating_light::rotating_light::test_tube: Smoke tests failed on *<https://docs.launchdarkly.com|Production>* :rotating_light::rotating_light::rotating_light:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failed run"
                    },
                    "action_id": "view-action-${{github.run_id}}",
                    "url": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": ":github: Deploy triggered by ${{github.actor}}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
