name: Sync repos from private to public
on: deployment_status
jobs:
  private-public-sync:
    if: ${{ github.event.deployment_status.environment == 'production' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    name: Private to public repo sync
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          # fetch entire history to get Last Edit date for topics
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: |
          git config --global user.email "launchdarklyreleasebot@launchdarkly.com"
          git config --global user.name "LaunchDarklyReleaseBot"
          git remote add public 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/LaunchDarkly-Docs.git'
          git fetch public

          if git pull public main --rebase; then
            git pull --rebase && git push
            echo "Successfully merged and pushed public changes to private repo. Will sync private to public now."
          else
            echo "Conflict detected. TODO: Using the GH cli, create a PR containing the conflicts to be resolved in private repo."
            exit 1
          fi
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/git-gatsby.git'
          source_branch: 'main'
          destination_repo: 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/LaunchDarkly-Docs.git'
          destination_branch: 'main'
