name: Scheduled link check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  check-external-links:
    # includes github
    name: Check external links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          fail: true
          args: --config .github/lychee-all.toml README.md src/content/topics/**/*.mdx src/content/topics/**/**/*.mdx src/content/topics/**/**/**/*.mdx src/content/topics/**/**/**/**/*.mdx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
